name: 'Hexo Action'
inputs:
  who_to_greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  deploy_key:
    description: 'The deploy key for Github Pages repo'
    required: true
    default: ''
  commit_msg:
    description: 'Git commit messages to your GitHub Pages repository.'
    required: false
    default: ''
outputs:
  notify: # id of output
    description: 'The notification of deployment result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who_to_greet }}
    - ${{ inputs.deploy_key }}
branding:
  icon: 'package'  
  color: 'blue'