# Use GitHub action to deploy hexo to the gh_page branch of the same repository
name: Hexo CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Step ① Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
    
    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Step ② Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Step ③ Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    # Deploy hexo blog website.
    - name: Step ④ Deploy
      id: deploy
      uses: ./.github/workflows # Uses an action in the root directory
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        commit_msg: ${{ github.event.head_commit.message }}  # (or delelte this input setting to use hexo default settings)

    - name: Step ⑤ Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
